- name: Create redis repo file
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: uninstall redis package
  ansible.builtin.yum:
    name: redis
    state: removed

- name: Install redis package
  ansible.builtin.yum:
    name: redis-6.2.7*
    state: installed
    allow_downgrade: yes

- name: update the bindIP
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis database
  ansible.builtin.systemd:
    name: redis-6.2.7*
    state: restarted
    enabled: yes

