#- name: Create an EC2 Instance using ansible
#  hosts: localhost
#  tasks:
#    - name: Create an EC2 Instance
#      amazon.aws.ec2:
#        instance_type: t3.micro
#        image: ami-0c88f8ebde436272a
#        wait: yes
#        group_id: sg-0bbb0b4aedca4a12f
#        region: us-east-1
#        count: 1
#        instance_tags:
#          Name: ansible-role-check-instance
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: t3.micro
    security_group_id: sg-0bbb0b4aedca4a12f
    image: ami-0c88f8ebde436272a
    region: us-east-1
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
        group_id: "{{ security_group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        instance_tags:
          Name: ansible-testing1
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_ip }}"
      wait_for_connection:
        delay: 30
        timeout: 120
      loop: "{{ ec2.instances }}"

- name: Run role to Test
  hosts: launched
  become: True
  gather_facts: True
  ignore_errors: yes
  roles:
    - "{{role_name}}"

- name: Terminate instances
  hosts: localhost
  tasks:
    - name: Terminate instances that were previously launched
      amazon.aws.ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
        region: us-east-1


