- name: Play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
- name: Play level variable from file
  hosts: all
  vars_file:
    - sample-vars.yml
  tasks:
    - name: Print URL from file
      ansible.builtin.debug:
        msg: URL = {{URL}}
