- name: Play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
- name: Play level variable from file
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL from file
      ansible.builtin.debug:
        msg: URL = {{URL}}
- name: Play level variable from tasks
  hosts: all
  tasks:
    - name: Print URL from tasks
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
        URL: tasks.example.com

- name: Variables from Inventory
  hosts: all
  tasks:
    - name: Print URL from Inventory
      ansible.builtin.debug:
        msg: URL = {{URL}}
- name: Variables from Predefined
  hosts: all
  tasks:
    - name: Print Architecture details
      ansible.builtin.debug:
        msg: Architecture = {{ansible_architecture}}, IP Address = {{ansible_eth0.ipv4.address}}