# yum install nginx -y
# systemctl enable nginx
# systemctl start nginx
#
# curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
#
# cd /usr/share/nginx/html
# rm -rf *
# unzip /tmp/frontend.zip
# mv frontend-main/* .
# mv static/* .
# rm -rf frontend-main README.md
# mv localhost.conf /etc/nginx/default.d/roboshop.conf
#
# systemctl restart nginx

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Download and Extract Frontend
  include_role:
    name: common
    tasks_from: download

- name: Clear the Frontend Files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy frontend content to nginx
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy roboshop config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart Nginx

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes