#  - Shipping Service
#
#    So we need to load that schema into the database, So those applications will detect them and run accordingly.
#
#    To download schema, Use the following command
#
#    ```bash
#    # curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
#    ```
#
#    Load the schema for Services.
#
#    ```bash
#    # cd /tmp
#    # unzip mysql.zip
#    # cd mysql-main
#    # mysql -u root -pRoboShop@1 <shipping.sql
##    ```

- name: Setup MySQL repos
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

- name: Start MySQL
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

# check if mysql new password is able to connect to server, if not connected then change the password
- name: Collect all possible information using passwordless root access
  mysql_info:
    login_user: root
    login_password: RoboShop@1
  ignore_errors: yes
  register: mysql_stat
#
#- name: Create Default root password
#  when: mysql_stat.failed
#  ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
#  register: DEFAULT_ROOT_PASSWORD
#
#- name: Copy the command to Set root password
#  when: mysql_stat.failed
#  ansible.builtin.copy:
#    src: rootpass.sql
#    dest: /tmp/rootpass.sql
#
#- name: Set the new root password
#  when: mysql_stat.failed
#  ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWORD.stdout}}" </tmp/rootpass.sql

# above commented statements can be written in block as below

- name: Block for resetting password
  when: mysql_stat.failed
  block:
    - name: Create Default root password
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: DEFAULT_ROOT_PASSWORD

    - name: Copy the command to Set root password
      ansible.builtin.copy:
        src: rootpass.sql
        dest: /tmp/rootpass.sql

    - name: Set the new root password
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWORD.stdout}}" </tmp/rootpass.sql

- name: check validate password plugin is removed
  ansible.builtin.shell: echo 'show plugins' | mysql -uroot -pRoboShop@1 | grep validate_password
  register: plugin_info
  ignore_errors: yes

- name: unsinstall validate password plugin
  when: plugin_info.rc == 0
  community.mysql.mysql_db:
    state: import
    name: all
    target: validatepass.sql
    login_user: root
    login_password: RoboShop@1

- name: Download and Extract MySQL
  include_role:
    name: common
    tasks_from: download

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: RoboShop@1
